# ======
# Project Details
# ======
name: 'dbt_scd_snapshot_sample'
version: '1.0.0'
config-version: 2
profile: 'dbt_sample'

vars:
  session_date: '{{ run_started_at.astimezone(modules.pytz.timezone("Asia/Tokyo")).strftime("%Y-%m-%d") }}'

dispatch:
  - macro_namespace: dbt-adapters
    search_order: ['dbt_scd_snapshot_sample', 'dbt-adapters']

# ======
# File Path Configs
# ======
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# ==================
# Test Configs
# ==================
data_tests:
  +severity: warn

# ==================
# Model Configs
# ==================
models:
  dbt_sample:
    +materialized: table

    salesforce_history:
      +target_database: my_project
      +target_schema: salesforce_snapshots
